### ISSUE TITLE
m2epro_ebay_magento connect package missing

### ISSUE THREAD

**Issue by Flyingmana** [magento-hackathon/composer-repository#116]
connect page: http://www.magentocommerce.com/magento-connect/ebay-magento-integration-order-import-and-stock-level-synchronization-also-supports-amazon-rakuten-and-play-com.html

connect 2.0 key: http://connect20.magentocommerce.com/community/m2epro_ebay_magento

Maybe an issue, because it has also a Magento GO package

reported by @kkoepke

**Comment by daim2k5** [comment]
fixed see http://packages.firegento.com/connect20/m2epro_ebay_magento.json
