### ISSUE TITLE
steverobbins/redismanager could not be found

### ISSUE THREAD

**Issue by steverobbins** [magento-hackathon/composer-repository#127]
Curious as to why this isn't working.  New to composer so sorry if this is a dumb question.

Here's the PR adding it to the repo: https://github.com/magento-hackathon/composer-repository/pull/101

Any my `composer.json`: https://github.com/steverobbins/Magento-Redismanager/blob/master/composer.json

Did I do something wrong?

**Comment by Flyingmana** [comment]
on this side everything works correct http://packages.firegento.com/#!/steverobbins

but you need to correctly tag releases, your tag is ```releases/v1.2.4``` but it should be ```v1.2.4``` or ```1.2.4```
