### ISSUE TITLE
Add older versions of ZetaPrints Fixedprices extension

### ISSUE THREAD

**Issue by cmckni3** [magento-hackathon/composer-repository#134]
This extension was on Magento Connect but I can't find it on Magento Connect anymore. I need an older version, 0.5.0 which is available at [TopMage](http://ext.topmage.com/ZetaPrints_Fixedprices.html).

I will gladly send a pull request but I would have to know the process to get this manually added to firegento. As far as I know, a git repo doesn't exist for it.

**Comment by daim2k5** [comment]
@cmckni3 do you mean "connect20/zetaprints_fixedprices" ? If a older version is not available then the tar archive is corrupt on the magento site. Sorry :-(

**Comment by cmckni3** [comment]
@daim2k5 That's the one. I'm not actually able to find the extension on magento connect at all and I'm not sure of the direct URL to download the extension.
