### ISSUE TITLE
Add MageMaven Order Comment

### ISSUE THREAD

**Issue by cmckni3** [magento-hackathon/composer-repository#137]
I would like the Order Comment extension added from Magento Commerce.

```
http://www.magentocommerce.com/magento-connect/magemaven-ordercomment.html
```

**Comment by cmckni3** [comment]
Appears the repo is on GitHub. https://github.com/r8/magento-order-comment

**Comment by daim2k5** [comment]
@cmckni3 so make a pull request to add a composer.json to https://github.com/r8/magento-order-comment. Then if the PR is merge make another one here to add this to packages.firegento.com

**Comment by cmckni3** [comment]
Instant merge?

**Comment by daim2k5** [comment]
I have a script that check if the composer is valid, if yes i get a notification and i can click on merge ;-)

**Comment by cmckni3** [comment]
Nice. Do I have to wait for it to be deployed to firegento?

**Comment by daim2k5** [comment]
Yes, the building script runs every hour

**Comment by cmckni3** [comment]
Sweet. I look forward to using it.

**Comment by cmckni3** [comment]
I'm guessing the tags for the versions aren't showing up on firegento because they are tags with a comment. Is this correct @daim2k5?

**Comment by daim2k5** [comment]
i think the tagged versions didn't have a composer.json

**Comment by cmckni3** [comment]
Ok. That makes sense.
