### ISSUE TITLE
Outdated modules?

### ISSUE THREAD

**Issue by Roywcm** [magento-hackathon/composer-repository#205]
I want to add some packages to my composer, but they are outdated in the registry. 
I'm understand this can happen due to corrupt tar packages.
But, in this case, I can download the packages via an "updated" link and extract them just fine?

For example Fishpig_wordpress:
Latest in firegento registry: 3.1.1.18. But when I open the link with the newest version:  http://connect20.magentocommerce.com/community/Fishpig_Wordpress_Integration/3.1.1.2/Fishpig_Wordpress_Integration-3.1.1.2.tgz  I can extract and read it just fine?

This also happen on the package connect20/sisowpayment

**Comment by daim2k5** [comment]
@Roywcm yes, this is correct but composer use Phar ;-) so if you tell me that you can open the tgz with phar and its not included in our list please reopen the issue

**Comment by Roywcm** [comment]
Too bad this does not work. 
What do you advise to do? Install those packages by hand?

**Comment by daim2k5** [comment]
yes :-(

**Comment by Schrank** [comment]
If the modules are open source, you can put them on github and then add them to your composer with your own repo. I don't recommend to add them to the satis, because they might be not maintained.
