### ISSUE TITLE
connect20/* links in http://packages.firegento.com are giving years old versions

### ISSUE THREAD

**Issue by kkoepke** [magento-hackathon/composer-repository#258]
The connect20/* Links for Magento Connect Links are not working correctly anymore. There are mostly only 2-3 year old versions in the repository and current updates are not recognized anymore.

An Example:
http://www.magentocommerce.com/magento-connect/baseprice-modul-basic-grundpreis-modul-pangv.html 
Current version in Magento Connect is 13.04.09 and in http://packages.firegento.com 0.3.0. There are 5 or 6 versions and like 1 year between them. On other extensions its even more.

**Comment by daim2k5** [comment]
We got every month the same bug report. Please be aware that we crawler the site. That it no magic no help from magento/ebay. Many problems are related with a bad header in the tar archive file and we can't fix the files.

**Comment by Schrank** [comment]
Maybe don't close the bug, so it is found easily and just mark it as won't fix?
