### ISSUE TITLE
GermanLocalPack has no versions

### ISSUE THREAD

**Issue by Schrank** [magento-hackathon/composer-repository#279]
In the package https://github.com/riconeitzel/German_LocalePack_de_DE are all versions missing, although a lot of tags are defined
![bildschirmfoto 2015-06-26 um 20 09 54](https://cloud.githubusercontent.com/assets/379680/8384165/7ee75b7e-1c3f-11e5-9bd7-12b155049b3a.png)
![bildschirmfoto 2015-06-26 um 20 10 48](https://cloud.githubusercontent.com/assets/379680/8384164/7ee708ae-1c3f-11e5-9744-83f3ee1335cb.png)

**Comment by daim2k5** [comment]
bad version schema see https://getcomposer.org/doc/04-schema.md#version
