### ISSUE TITLE
Cannot read packages repository.

### ISSUE THREAD

**Issue by andkirby** [magento-hackathon/composer-repository#301]
I got an error on read packages from the repository http://packages.firegento.com/.
```
  [Composer\Downloader\TransportException]
  The "http://packages.firegento.com/include/all$96a531fefda653de2a0a30df9e8fa97e1a435a59.json" file could
   not be downloaded (HTTP/1.1 404 Not Found)
```

I've rechecked `packages.json` and it has a link to `include/all$96a531fefda653de2a0a30df9e8fa97e1a435a59.json`. So, looks like everything is correct excepting an access to the file.

**Comment by daim2k5** [comment]
Hi, sorry there was an error with a package and i don't saw me own notification :-( Here in Germany is the CDN up2date so please try again.

**Comment by andkirby** [comment]
Hi, yeah, it works fine now. Thank you!
