### ISSUE TITLE
Add connect 20 module 

### ISSUE THREAD

**Issue by samuelecarpene** [magento-hackathon/composer-repository#302]
Hi.
I want to add http://www.magentocommerce.com/magento-connect/catalog-search-terms-ip-filter.html to firegento.
I navigated in the connect and the package is located here.
http://connect20.magentocommerce.com/community/Acegento_Ratingfilter/0.1.0/Acegento_Ratingfilter-0.1.0.tgz
but i don't know how to add it to satis.json.

Is possible to do this taking as example the "connect20/interface_frontend_rwd_default" module?
```
{
		"type": "package",
		"package": {
				"name": "connect20/zero1_searchipfilter",
				"version": "0.1.0",
				"dist": {
						"type": "tar",
						"url": "http://freegento.com/magento-extensions/Zero1_Searchipfilter-1.0.0.0.tgz",
						"reference": null,
						"shasum": null
				},
				"require": {
						"magento-hackathon/magento-composer-installer": "*"
				},
				"type": "magento-module",
				"extra": {
						"package-xml": "package.xml"
				}
		}
},
```
This piece of code is correct?

Thank you.

**Comment by daim2k5** [comment]
The original package can't be unzip be phar so ne we can't add this packages. Sorry.
