### ISSUE TITLE
connect20/aw_blog is out of date

### ISSUE THREAD

**Issue by clockworkgeek** [magento-hackathon/composer-repository#303]
The latest version was [released 11 days ago](http://www.magentocommerce.com/magento-connect/blog-community-edition-by-aheadworks.html) and still isn't listed.  Could there be other missing updates from Connect?

**Comment by daim2k5** [comment]
we update only once in a month the connect20 packages. Next schedule is tommorow

**Comment by clockworkgeek** [comment]
Now I have egg on my face.

**Comment by daim2k5** [comment]
update done.
