### ISSUE TITLE
Package not fount

### ISSUE THREAD

**Issue by siamro** [magento-hackathon/composer-repository#321]
Hello,
today i cant use composer.
Error:

 [Composer\Downloader\TransportException]                                     
  The "http://packages.firegento.com/include/all$bbb86f8c3903469f05b976cc60da0c2d066051fd.json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by daim2k5** [comment]
I know :-(  see https://twitter.com/daim2k5/status/643158245205508096

**Comment by siamro** [comment]
Do You know how much time may pass to fix it?

**Comment by davidverholen** [comment]
maybe now its time to use https://github.com/composer/packagist ? ;)

**Comment by siamro** [comment]
It may be a good idea ^^

**Comment by barryvdh** [comment]
I have the same issue. Is the build corrupted or something?

**Comment by siamro** [comment]
It seems there is no package bbb86f8c3903469f05b976cc60da0c2d066051fd.json on http://packages.firegento.com/include.

**Comment by shoaibrehman** [comment]
I have the same error when I try to deploy code on our staging: I get this error:

**Comment by daim2k5** [comment]
Working on it. Got i hacky solution hopefully the CDN update get really fast

**Comment by barryvdh** [comment]
Seems to be working for me now.

**Comment by siamro** [comment]
Not for me.

**Comment by Magepim** [comment]
Still getting the error.  Presume we need to wait for the CDN to fully update?

**Comment by daim2k5** [comment]
yes

**Comment by shoaibrehman** [comment]
nope, not for me. Let's wait for the CDN to update.

**Comment by reiser** [comment]
hey seems to be back again. dankeschön damian :-) http://packages.firegento.com/include/all$99cb065d44da55a76609f645b3d70f8cc2a3895c.json

**Comment by siamro** [comment]
http://packages.firegento.com/include/all$bbb86f8c3903469f05b976cc60da0c2d066051fd.json
Still doesnt works :P

**Comment by shoaibrehman** [comment]
I wonder why this issue is closed. It hasn't been fixed yet. I still get the same error. Any idea what's wrong?

**Comment by daim2k5** [comment]
Please wait for the CDN to update

**Comment by shoaibrehman** [comment]
Thank you for the update @daim2k5

**Comment by Magepim** [comment]
Working now on most of my servers.  Thanks Damian.

**Comment by shoaibrehman** [comment]
Working now. Thank you.

**Comment by siamro** [comment]
Oh now mine composer f*cked up completely

**Comment by shoaibrehman** [comment]
@siamro  are you experiencing the same min stability issue? I am experiencing package compability issues now.

**Comment by siamro** [comment]
Nvm. I pull and install whole project again and it works now ^^

**Comment by shoaibrehman** [comment]
@daim2k5 I am experiencing probelms with my code deployment since you fixed the issue. I never had any issues regarding min-stability but since this issue is fixed, the composer don't seem to install anything. Could you help me fix this issue please? 

ERROR trace below: 

Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)         Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/magento-composer-installer 0.1.3 requires eloquent/composer-config-reader 2.* -> no matching package found.
    - magento/magento-composer-installer 0.1.2 requires eloquent/composer-config-reader 2.* -> no matching package found.
    - magento/magento-composer-installer 0.1.1 requires eloquent/composer-config-reader 2.* -> no matching package found.
    - magento/magento-composer-installer 0.1.0 requires eloquent/composer-config-reader 2.* -> no matching package found.
    - redboxdigital/websiterestriction dev-next-release requires magento-hackathon/magento-composer-installer * -> satisfiable by magento-hackathon/magento-composer-installer[0.1.0, 0.1.1, 0.1.2, 0.1.3].
    - magento-hackathon/magento-composer-installer 0.1.3 requires magento/magento-composer-installer 0.1.3 -> satisfiable by magento/magento-composer-installer[0.1.3].
    - magento-hackathon/magento-composer-installer 0.1.2 requires magento/magento-composer-installer 0.1.2 -> satisfiable by magento/magento-composer-installer[0.1.2].
    - magento-hackathon/magento-composer-installer 0.1.1 requires magento/magento-composer-installer 0.1.1 -> satisfiable by magento/magento-composer-installer[0.1.1].
    - magento-hackathon/magento-composer-installer 0.1.0 requires magento/magento-composer-installer 0.1.0 -> satisfiable by magento/magento-composer-installer[0.1.0].
    - Installation request for redboxdigital/websiterestriction dev-next-release -> satisfiable by redboxdigital/websiterestriction[dev-next-release].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by daim2k5** [comment]
the packages is not include at the moment, random timeout means random packages are not included :-( Sorry i try to resolve the problem but i need time between job and all other stuff :-(

**Comment by shoaibrehman** [comment]
Sorry, I don't understand that. So you mean that you are aware of the issue and it can be fixed? IS there anything I could do to fix this issue and save your time ?

**Comment by daim2k5** [comment]
yes iam aware of the issue and it can be fixed. But i can't give you a timeline

**Comment by shoaibrehman** [comment]
What is the quickest possible solution because at the moment I cannot deploy anything and our staging website is down. I really want to get it working. Thank you for your help.

**Comment by daim2k5** [comment]
Me too i wait now for feedback from github

**Comment by shoaibrehman** [comment]
Thank you, please update us when you have fixed it.

**Comment by daim2k5** [comment]
So i managed one complete run and upload the stuff oldschool via FTP ;-) Hopefully all packages are now included.

**Comment by daim2k5** [comment]
@shoaibrehman can you give me feedback? works again?

**Comment by shoaibrehman** [comment]
Hi Damien,

Thank you for taking a look on it. Apologies I was on a holiday.

Yes, it worked absolutely fine. Excellent work. Thank you very much for your help and fixing that issue. Much appreciated.



Sent from my Samsung Galaxy Note III - powered by Three


-------- Original message --------
