### ISSUE TITLE
Project dependany issue - The package is not available in a stable-enough version according to your minimum-stability 

### ISSUE THREAD

**Issue by shoaibrehman** [magento-hackathon/composer-repository#322]
I am experiencing probelms with my code deployment since you fixed the issue. I never had any issues regarding min-stability but since this issue is fixed, the composer don't seem to install anything. Could you help me fix this issue please?

ERROR trace below:

Loading composer repositories with package information Updating dependencies (including require-dev) Your requirements could not be resolved to an installable set of packages.

Problem 1
- magento/magento-composer-installer 0.1.3 requires eloquent/composer-config-reader 2.* -> no matching package found.
- magento/magento-composer-installer 0.1.2 requires eloquent/composer-config-reader 2.* -> no matching package found.
- magento/magento-composer-installer 0.1.1 requires eloquent/composer-config-reader 2.* -> no matching package found.
- magento/magento-composer-installer 0.1.0 requires eloquent/composer-config-reader 2.* -> no matching package found.
- redboxdigital/websiterestriction dev-next-release requires magento-hackathon/magento-composer-installer * -> satisfiable by magento-hackathon/magento-composer-installer[0.1.0, 0.1.1, 0.1.2, 0.1.3].
- magento-hackathon/magento-composer-installer 0.1.3 requires magento/magento-composer-installer 0.1.3 -> satisfiable by magento/magento-composer-installer[0.1.3].
- magento-hackathon/magento-composer-installer 0.1.2 requires magento/magento-composer-installer 0.1.2 -> satisfiable by magento/magento-composer-installer[0.1.2].
- magento-hackathon/magento-composer-installer 0.1.1 requires magento/magento-composer-installer 0.1.1 -> satisfiable by magento/magento-composer-installer[0.1.1].
- magento-hackathon/magento-composer-installer 0.1.0 requires magento/magento-composer-installer 0.1.0 -> satisfiable by magento/magento-composer-installer[0.1.0].
- Installation request for redboxdigital/websiterestriction dev-next-release -> satisfiable by redboxdigital/websiterestriction[dev-next-release].

Potential causes:

    A typo in the package name
    The package is not available in a stable-enough version according to your minimum-stability setting see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by daim2k5** [comment]
Have you still the problem?

**Comment by shoaibrehman** [comment]
No @daim2k5 , It was fixed the other day. 

Cheers
