### ISSUE TITLE
Wrong File References (404)

### ISSUE THREAD

**Issue by ernsto** [magento-hackathon/composer-repository#343]
Hello, 

i want to inform you, that currently the references to the project JSON files are not correct. 

Please look at your generated packages.json at http://packages.firegento.com/packages.json. 
There are some references on JSON Files which does not exist. 

Example: 
![image](https://cloud.githubusercontent.com/assets/8912877/11363606/23b3a636-929b-11e5-97d2-9720ff19dbd2.png)
Composer will try to download the project information from this file: 
- http://packages.firegento.com/AWeberCommunications_EmailMarketing.json

Unfortunatelly this file does not exist: 
![image](https://cloud.githubusercontent.com/assets/8912877/11363626/4d2a71a2-929b-11e5-9cd5-c96c647ccd50.png)

When i try to build my projects with "composer install", an exception is thrown (404). Therefore is is currently not possible to build a composer Project when the composer repository http://packages.firegento.com is used. 

Could you please try to rebuild the JSON Files? 
```
php bin/satis build <configuration file> <build-dir>
```
Source: https://github.com/composer/satis/blob/master/README.md

**Comment by daim2k5** [comment]
see #342
