### ISSUE TITLE
Missing connect20/fishpig_wordpress_integration repo

### ISSUE THREAD

**Issue by danemacmillan** [magento-hackathon/composer-repository#346]
The `connect20/fishpig_wordpress_integration` repo is missing from http://packages.firegento.com/#!/fishpig.

This might be a similar issue to what happened a few days back in #342.

**Comment by daim2k5** [comment]
I think Magento delete the package from the marktplace. Sorry we don't have a mirror

**Comment by magentix98** [comment]
I still cannot find "connect20/fishpig_wordpress_integration".
Has this problem been fixed?

**Comment by perspektiveweb** [comment]
For me it finds the packages but then is unable to download from 

`https://connect20.magentocommerce.com/community/Fishpig_Wordpress_Integration/4.2.0.16/Fishpig_Wordpress_Integration-4.2.0.16.tgz"`

Error is: Connection reset by peer, Failed to enable crypto.

I already messed around with specifying pem files and downloading the cacert.pem for hours. It works just fine with other firegento packages. Specifically https://connect20... downloads won't work.
