### ISSUE TITLE
Error 404 connect20/cashondelivery

### ISSUE THREAD

**Issue by tniebergall** [magento-hackathon/composer-repository#348]
If i try to install connect20/cashondelivery i get the following error

[Composer\Downloader\TransportException]                                                                                                                  
  The "http://connect20.magentocommerce.com/community/CashOnDelivery/0.4.3/CashOnDelivery-0.4.3.tgz" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by daim2k5** [comment]
I have the same error, also http://ext.topmage.com/extensions/5b/c9/CashOnDelivery/?C=M;O=A has the same problem. I think Magento deleted the package
