### ISSUE TITLE
dermodpro_baseprice removed?

### ISSUE THREAD

**Issue by tniebergall** [magento-hackathon/composer-repository#349]
Is there a reason why connect20/dermodpro_baseprice isn't available anymore?

**Comment by Schrank** [comment]
Afaik @Vinai removed all his modules from connect, not sure whether this counts for the one distributed by netresearch too.

But you can find a bunch of repos on bitbucket: https://bitbucket.org/repo/all?name=baseprice

**Comment by tniebergall** [comment]
Okay thanks I'll have a look.

**Comment by Vinai** [comment]
That isn't one of my modules any more, it has nothing to do with me removing my modules from Magento Connect.

**Comment by Vinai** [comment]
Actually, all my modules are still available on MC, even after I removed them. The code of them is rather outdated in the meanwhile, but Magento didn't actually delete the packages. They only hid them from the Web interface so they no longer where installable by "normal" Magento Connect means.

**Comment by Vinai** [comment]
Oh, any module in the DerModPro namespace is owned by Netresearch, not me, even if I originally created them.
