### ISSUE TITLE
Shopgo_GTM module archives missed

### ISSUE THREAD

**Issue by rakshazi** [magento-hackathon/composer-repository#361]
Hello!
Package: connect20/shopgo_gtm
Affected versions: all
Problem: 404 error on *.tgz archive
Example: http://connect20.magentocommerce.com/community/Shopgo_GTM/1.0.4/Shopgo_GTM-1.0.4.tgz
How to reproduce: add `"connect20/shopgo_gtm": "^1.0.2"` to "require" section of your composer.json

**Comment by rakshazi** [comment]
any update on this?

**Comment by tariqmth** [comment]
Anyone gonna look at that ?

**Comment by Schrank** [comment]
We are reading every ticket carefully, please be patient. We are doing this all in our spare time.

**Comment by Flyingmana** [comment]
they got likely deleted from magento connect. In that case we can not help.

**Comment by rakshazi** [comment]
ok, can you remove this package from your repo, please?

**Comment by daim2k5** [comment]
i run a full connect20 update.

**Comment by tariqmth** [comment]
Hi daim2k5
The issue is still there, may be you got to remove it update it manually or delete it.

**Comment by daim2k5** [comment]
The extension is not available , see http://packages.firegento.com/#!/shopgo. Please remove it from your composer.json
