### ISSUE TITLE
Change Magento Connect download links to HTTPS

### ISSUE THREAD

**Issue by aadmathijssen** [magento-hackathon/composer-repository#366]
Since the [Composer beta1 release](https://github.com/composer/composer/releases/tag/1.0.0-beta1) of 03-03-2016 the use of unsecure url's is prohibited by default. See also the [documentation](https://getcomposer.org/doc/06-config.md#secure-http) of the `secure-http` config option.

This affects the Firegento repository, because all packages that are downloaded from Magento Connect are downloaded via HTTP. When looking at the current includes link in the content of https://packages.firegento.com/packages.json, there are 11.869 links to `connect20.magentocommerce.com`, all of them using HTTP.

To resolve this, all references to `http://connect20.magentocommerce.com` need to be replaced by `https://connect20.magentocommerce.com`

**Comment by daim2k5** [comment]
fixed.

**Comment by aadmathijssen** [comment]
Thanks!
