### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by samuelecarpene** [magento-hackathon/composer-repository#381]
I don't understand why some new version app packages are not listed in the repository.
For example "Jmango360" (https://www.magentocommerce.com/magento-connect/jmango360-rest-plugin.html) is stopped to 2.2.1 version but if you look at connect you can see that the newest version of the app is 2.4.1.

![image](https://cloud.githubusercontent.com/assets/3714185/15040106/4955736e-12b2-11e6-9d48-fbd800464ce8.png)

![image](https://cloud.githubusercontent.com/assets/3714185/15040120/62380e78-12b2-11e6-8936-fd4624484917.png)

In fact  you can download the new version 2.4.1 (https://connect20.magentocommerce.com/community/Jmango360_Japi/2.4.1/Jmango360_Japi-2.4.1.tgz)

**Comment by FreshFlesh** [comment]
Same issue here with other modules. Some updates seem to be missing?

**Comment by daim2k5** [comment]
Again, its a manuell process. If i have time i update the connect20 packages. Last update was this night

**Comment by barryvdh** [comment]
Would it be possible to run this as cron, so it will be updated automatically every day?

**Comment by Flyingmana** [comment]
no, this is not using an official API, so please be modest and thankfully for every day we dont get the current way of receiving them blocked
