### ISSUE TITLE
Ogone extension is renamed in the Magento Marketplace

### ISSUE THREAD

**Issue by ArjenMiedema** [magento-hackathon/composer-repository#386]
The Ogone extension (connect20/ogone) has been renamed in the Magento Marketplace. The package URLs used to be like this: `connect20.magentocommerce.com/community/Ogone/xx.xx.xx/Ogone-xx.xx.xx.tgz`. But they renamed it to Ogone_ePayments. So the new URLs should be like `connect20.magentocommerce.com/community/Ogone_ePayments/xx.xx.xx/Ogone_ePayments-xx.xx.xx.tgz`.

Is it possible to update this, so the Ogone extension can be updated and installed again via composer. Thanks in advance.

**Comment by daim2k5** [comment]
Hi @ArjenMiedema connect20/ogone_epayments is now available
