### ISSUE TITLE
old Fishpig versions and freegento

### ISSUE THREAD

**Issue by zainengineer** [magento-hackathon/composer-repository#396]
Old Fishpig urls no longer work for example for example

https://connect20.magentocommerce.com/community/Fishpig_Wordpress_Integration/3.1.1.1/Fishpig_Wordpress_Integration-3.1.1.1.tgz

newer versions work https://connect20.magentocommerce.com/community/Fishpig_Wordpress_Integration/4.2.0.16/Fishpig_Wordpress_Integration-4.2.0.16.tgz

I  understand it is problem of `connect20` but some how freegento works. 
http://freegento.com/magento-extensions/Fishpig_Wordpress_Integration-3.1.1.11.tgz
Do we know how freegento fixes the issue? can we implement something like it?

**Comment by daim2k5** [comment]
Synced today. Sorry for the delay
