### ISSUE TITLE
Newer module version from Magento Connect available

### ISSUE THREAD

**Issue by riker09** [magento-hackathon/composer-repository#397]
There is a newer version available for module [I-Ways PayPal Plus](https://www.magentocommerce.com/magento-connect/paypal-plus-1-1.html)  on magento connect. Version 1.8.0 to be precise (vs. 1.7.3 in FireGento repository). According to their changelog this version was published a couple of days ago, but it is not available on the FireGento repository.

How often is the repo synchronized with Magento Connect?

**Comment by barryvdh** [comment]
A new sync would be nice indeed :)
In my case it is connect20/aw_blog which released v1.3.18 with possible SQL injection fix (released august 31)

**Comment by daim2k5** [comment]
Synced today. Sorry for the delay

**Comment by barryvdh** [comment]
Thanks! No problem :)
