### ISSUE TITLE
Magento Connect Sync

### ISSUE THREAD

**Issue by rayphi** [magento-hackathon/composer-repository#400]
There are a few new versions available for module [connect20/gene_braintree](https://www.magentocommerce.com/magento-connect/braintree-payments-with-hosted-fields.html) on magento connect:

- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3 

Is it possible to trigger a new sync?

**Comment by hans2103** [comment]
Same goes for module connect20/tig_postnl

Current version here is 1.7.2

Most recent verseion on Magento Connect is 1.10.1

https://www.magentocommerce.com/magento-connect/postnl-extension-for-magento.html
Version 1.10.1
2016-11-11 08:18:32

Is it possible to trigger a new sync?

**Comment by daim2k5** [comment]
@rayphi sorry, no
@hans2103 sorry, no

please wait the sync happens every month once
