### ISSUE TITLE
Update connect20/et_russianlanguagepack to 1.5.5

### ISSUE THREAD

**Issue by mrmoonlv** [magento-hackathon/composer-repository#425]
Please update connect20/et_russianlanguagepack

Last version in https://marketplace.magento.com/etws-et-russianlanguagepack.html is 1.5.5.
Here is a link to module:
https://connect20.magentocommerce.com/community/ET_RussianLanguagePack/1.5.5/ET_RussianLanguagePack-1.5.5.tgz

Thanks.

**Comment by daim2k5** [comment]
Fixed. Please wait some hours for the rebuild
