### ISSUE TITLE
Update connect20/fooman_emailattachments to 0.9.6

### ISSUE THREAD

**Issue by mrmoonlv** [magento-hackathon/composer-repository#426]
Please connect20/fooman_emailattachments

Last version in https://marketplace.magento.com/fooman-fooman-emailattachments.html is 0.9.6
Here is a link to module:
https://connect20.magentocommerce.com/community/Fooman_EmailAttachments/0.9.6/Fooman_EmailAttachments-0.9.6.tgz

Thanks.

**Comment by daim2k5** [comment]
We don't sync with the marketplace, we sync only the pear stuff to connect20
