### ISSUE TITLE
https

### ISSUE THREAD

**Issue by Schrank** [magento-hackathon/composer-repository#429]
Thanks to @frostblogNet
> Moin auf packages,firegento.com steht
> For global use: composer.phar config -g repositories.firegento composer http://packages.firegento.com
> 
> mit https wäre besser.
>  For global use: composer.phar config -g repositories.firegento composer https://packages.firegento.com
> 
> Gruß
> 
> Jens

I don't know how to change this - can I juse edit the index.html?

**Comment by daim2k5** [comment]
Fixed
