### ISSUE TITLE
Problem with connect20/magebuzz_free_testimonial 0.1.2

### ISSUE THREAD

**Issue by spectralshadow514** [magento-hackathon/composer-repository#430]
[ErrorException]  Source /var/www/public/vendor/connect20/Magebuzz_Free_Testimonial/app/code/local/frontend/default/default/css/magebuzz/testimonial.css does not exist.
I'm not sure if this is on your end, as it occurs when it happens directly after generating autoload files.

I know there's also a newer version, but that 404's which is on their end, so.. Ignore that.

**Comment by daim2k5** [comment]
Hi @spectralshadow514 
its not our end. We provide only the download for the magento connect packages.
