### ISSUE TITLE
Buckaroo version contstraints break older version of composer

### ISSUE THREAD

**Issue by tim-reynolds** [magento-hackathon/composer-repository#438]
Because of constraints we cannot control we are forced to use an order version of Composer. Currently we are restricted to 1.0.0-alpha10. We would need to investigate if newer versions would be compatible with some of our constraints... 

That being said, the recent addition of the tig/buckaroo modules has broken composer in all of our environments. Their format for specifying version constraints is not compatible with our composer version. 

Just hoping to open a dialog here about what specific version of composer we wish to support going forward and if we should have any defined limitations of feature use in the composer.json files that are included in this repository.

**Comment by tim-reynolds** [comment]
Of note we tested the newest version but it conflicted with other restrictions. Then we tested 1.0.0 final release and it worked with the tig/Buckaroo version constraints, so we are unblocked.

**Comment by Cloverdom** [comment]
Experiencing the same problem, unable to deploy to our servers due to Buckaroo version contstraints breaking older version of composer (which we have to use).

**Comment by daim2k5** [comment]
I removed the entries. Thanks for reporting the issue.
