### ISSUE TITLE
About syncing packages

### ISSUE THREAD

**Issue by mozgbrasil** [magento-hackathon/composer-repository#447]
Good Morning

The following are discrepant versions

In

http://packages.firegento.com/#!/searchanise

We have version 3.1.5

But the latest version is 3.1.7

According

https://marketplace.magento.com/searchanise-simtech-searchanise.html

Please, you can do this update

**Comment by daim2k5** [comment]
We cannot update the connect20 anymore because magento doesn't give us the data :-(

**Comment by mozgbrasil** [comment]
Good Morning

Thank you my friend

**Comment by daim2k5** [comment]
I need to find another good/stable way
