### ISSUE TITLE
The "https://packages.firegento.com/include/all%2443038064029abf0c5df83eaf3766a78f1c308b43.json" file could not be downloaded (HTTP/1.1 404 Not Found)

### ISSUE THREAD

**Issue by n3o77** [magento-hackathon/composer-repository#458]
I'm getting the error that this file can't be found? Is this just a bug?

**Comment by gpaddis** [comment]
I am getting the same error since this morning. I think the Firegento repository is broken, after a `composer clear-cache` the updates don't work anymore: https://twitter.com/aadmathijssen/status/1062766325032984578

**Comment by FrankStappers** [comment]
We are suffering from the same problem since yesterday.

**Comment by daim2k5** [comment]
I'm checking...

**Comment by daim2k5** [comment]
Did you still get the error?

**Comment by arosenhagen** [comment]
yes - error still persist

**Comment by daim2k5** [comment]
Its seems there is a new server in town :-( i try to contact the new server admin. Sorry :-(

**Comment by mautz-et-tong** [comment]
Hi, the packagist failed due to an invalid auth.json. I am rebuilding the json right now. Sorry for the inconvenience

**Comment by ProxiBlue** [comment]
No problem, Thank YOU for keeping on maintaining this!

The outage DID get me to finally get round to setup of own local satis mirror...

**Comment by gpaddis** [comment]
Thank you @mautz-et-tong everything is working now! :)

**Comment by mautz-et-tong** [comment]
There are still not all packages up to date. Please be careful. I will update here as soon as the rebuilding process is done

**Comment by mautz-et-tong** [comment]
So, the json files have been successfully written.
