### ISSUE TITLE
Create a review process to avoid evil behavior

### ISSUE THREAD

**Issue by Flyingmana** [magento-hackathon/composer-repository#76]
Some people just noticed, that the package system is so complex, it already looks for alias and replacement packages when a requirement could not get fulfilled.

https://twitter.com/alanstorm/status/460536715065569280

After this there came some remarks like

* deactivate packagist by default: https://twitter.com/alanstorm/status/460547475133050880
* this is a security problem: https://twitter.com/daniel_sloof/status/460542144009502720

As the firegento packages currently dont get reviewed besides if they break something, there should get a review process added, which reviews everything a source would add to the repository, as a single additional branch would allow to add arbitrary packages.

some more documentation:
http://blog.naderman.de/2014/02/17/replace-conflict-forks-explained/

**Comment by daim2k5** [comment]
I start to implement some stuff to check composer.json .... hopefully the error rates goes down ;-)
